FROM amazoncorretto:19-alpine-jdk
VOLUME /tmp
ARG JAR_FILE
ARG AGENT_ARG
ENV AGENT_ENV=${AGENT_ARG}
ARG NEWSGEARS_DEVELOPMENT
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_DATASOURCE_SCHEMA
ARG SPRING_REDIS_HOST
ARG SPRING_REDIS_PASSWORD
ARG NEWS_API_KEY
ARG NEWS_API_DISABLED
ARG NEWS_API_DEBUG_SOURCES
COPY ${JAR_FILE} app.jar
ENV NEWSGEARS_DEVELOPMENT false
ENV SPRING_DATASOURCE_URL jdbc:postgresql://feedgears-db01:5432/postgres
ENV SPRING_DATASOURCE_USERNAME postgres
ENV SPRING_DATASOURCE_PASSWORD postgres
ENV SPRING_DATASOURCE_SCHEMA classpath:/schema.sql
ENV SPRING_REDIS_HOST feedgears-cache01
ENV SPRING_REDIS_PASSWORD redis
ENTRYPOINT java ${AGENT_ENV} -Djava.security.egd=file:/dev/./urandom -jar /app.jar
